version: "3.8"

services:
  java-ci-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - .:/usr/app
      - ./private-key.pem:/usr/app/private-key.pem
      - ./database.db:/usr/app/database.db
    environment:
      - PRIVATE_KEY_PATH=/usr/app/private-key.pem
      - DATABASE_PATH=/usr/app/database.db
      - APP_ID=${APP_ID} # read from .env file
